export const dummyData = [
    {
        id: "1",
        category: "pop",
        writer: "해리",
        title: "음악 추천합니다",
        content: "들어보세요!",
        date: "2024-01-01",
        // 이미지? 영상 섬네일 - 주소도 필요
    },
    {
        id: "2",
        category: "classicAjazz",
        writer: "지민",
        title: "음악",
        content: "들어보세요!",
        date: "2024-01-01",
    },
    {
        id: "3",
        category: "pop",
        writer: "명환",
        title: "음악 추천",
        content: "들어보세요!",
        date: "2024-01-01",
    },
    {
        id: "4",
        category: "classicAjazz",
        writer: "혜련",
        title: "음악 추천합니다",
        content: "들어봐!",
        date: "2024-01-02",
    },
    {
        id: "5",
        category: "pop",
        writer: "해리2",
        title: "음악 추천합니다",
        content: "들어보세요!",
        date: "2024-01-01",
    },
    {
        id: "6",
        category: "classicAjazz",
        writer: "혜련2",
        title: "음악 추천합니다",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "7",
        category: "pop",
        writer: "혜련2",
        title: "음악 추천합니다",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "8",
        category: "classicAjazz",
        writer: "혜련2",
        title: "음악 추천합니다",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "9",
        category: "pop",
        writer: "혜련2",
        title: "음악 추천합니다",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "10",
        category: "classicAjazz",
        writer: "혜련2",
        title: "음악 추천합니다",
        content: "들어보세요!",
        date: "2024-01-03",
    },
];
