export const dummyData = [
    {
        id: "1",
        category: "팝",
        writer: "해리",
        title: "두아리파 신곡!",
        content: "너무 좋아요",
        date: "2024-01-01",
        // 이미지? 영상 섬네일 - 주소도 필요
    },
    {
        id: "2",
        category: "클래식및재즈",
        writer: "지민",
        title: "쇼팽 녹턴 1번",
        content: "들어보세요!",
        date: "2024-01-01",
    },
    {
        id: "3",
        category: "팝",
        writer: "명환",
        title: "Viva La Vida",
        content: "들어보세요!",
        date: "2024-01-01",
    },
    {
        id: "4",
        category: "클래식및재즈",
        writer: "혜련",
        title: "JAZZ 추천",
        content: "좋아요",
        date: "2024-01-02",
    },
    {
        id: "5",
        category: "클래식및재즈",
        writer: "해리2",
        title: "이 재즈 플리 어때요",
        content: "들어보세요!",
        date: "2024-01-01",
    },
    {
        id: "6",
        category: "클래식및재즈",
        writer: "혜련2",
        title: "드뷔시 음악",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "7",
        category: "팝",
        writer: "혜련2",
        title: "Sabrina Carpenter - Nonsense",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "8",
        category: "클래식및재즈",
        writer: "혜련2",
        title: "Ella Fitzgerald - Misty",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "9",
        category: "팝",
        writer: "보라돌이",
        title: "블랙핑크 노래",
        content: "들어보세요!",
        date: "2024-01-03",
    },
    {
        id: "10",
        category: "클래식및재즈",
        writer: "뚜비",
        title: " The Greatest Hits of Bill Evans",
        content: "들어보세요!",
        date: "2024-01-03",
    },
];
